AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Ascenda Template

Globals:
  Function:
    MemorySize: 128
    Architectures: ["arm64"]
    Handler: bootstrap
    Runtime: provided.al2
    Timeout: 5

Resources:
  AscendaApi:
      Type: AWS::Serverless::HttpApi
      Properties:
        StageName: Prod
        Auth:
          DefaultAuthorizer: AWS_IAM
          EnableIamAuthorizer: true

  GetPointsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/get-points/
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref AscendaApi
            Auth:
              Authorizer: AWS_IAM
            Path: /points
            Method: GET
    Metadata:
      BuildMethod: makefile

  GetUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/get-users/
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref AscendaApi
            Auth:
              Authorizer: AWS_IAM
            Path: /users
            Method: GET
    Metadata:
      BuildMethod: makefile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AscendaAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${AscendaApi}.execute-api.${AWS::Region}.amazonaws.com/points"
  GetPointsFunctionARN:
    Description: "First Lambda Function ARN"
    Value: !GetAtt GetPointsFunction.Arn
