AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Ascenda Template

Globals:
  Function:
    MemorySize: 128
    Architectures: ["arm64"]
    Handler: bootstrap
    Runtime: provided.al2
    Timeout: 5

Resources:
  GetPointsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/get-points/
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /points
            Method: GET
    Metadata:
      BuildMethod: makefile

  UpdatePointsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/update-points/
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /points
            Method: PUT
    Metadata:
      BuildMethod: makefile
  
  CreatePointsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/create-points/
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /points
            Method: POST
    Metadata:
      BuildMethod: makefile

  GetUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/get-users/
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /users
            Method: GET
    Metadata:
      BuildMethod: makefile

  # CreateUsersFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: functions/create-users/
  #     Events:
  #       Api:
  #         Type: HttpApi
  #         Properties:
  #           Path: /users
  #           Method: POST
  #   Metadata:
  #     BuildMethod: makefile

  # UpdateUsersFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: functions/update-users/
  #     Events:
  #       Api:
  #         Type: HttpApi
  #         Properties:
  #           Path: /users
  #           Method: PUT
  #   Metadata:
  #     BuildMethod: makefile

  DeleteUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/delete-users/
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /users
            Method: DELETE
    Metadata:
      BuildMethod: makefile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AscendaAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/points"
  GetPointsFunctionARN:
    Description: "First Lambda Function ARN"
    Value: !GetAtt GetPointsFunction.Arn
