name: CD Workflow
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - uses: aws-actions/setup-sam@v2
        
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Build Changes 
        run: |
          changed_folders=$(git diff --name-only HEAD^ HEAD | grep '^functions/' | cut -d'/' -f2 | sort -u)
          # Check if the list is empty
          if [ -z "$changed_folders" ]; then
            echo "No folders have changed. Running default build command."
            # Run a default make build command
            make build  
          else
            # Loop through the changed folders and execute build commands
            for folder in $changed_folders; do
              make_command="make build-$folder" 
              echo "Running command: $make_command"
              $make_command
            done
          fi

      - name: Deploy to AWS
        run: make deploy-auto