name: CD Workflow
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - uses: aws-actions/setup-sam@v2
        
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Build folder changes 
        run: |
          changed_folders=$(git diff --name-only HEAD^ HEAD | grep '^functions/' | cut -d'/' -f2 | sort -u)
          echo "Changed folders: $changed_folders"
          for folder in $changed_folders; do
            make_command="make build-$folder" 
            $make_command
          done

      - name: Deploy to AWS
        run: make deploy-auto